### ISSUE TITLE
Build schlägt fehl mit Boardverwalter ESP8266 v2.3 und Arduino 1.8.5

### ISSUE THREAD

**Issue by tbaetzler** [fablab-ka/PHABLABS-POV#1]
Fehler beim Build:

C:\Users\My\Documents\Arduino\libraries\ESPAsyncUDP\src\AsyncUDP.cpp: In member function 'bool AsyncUDP::listenMulticast(ip_addr_t*, uint16_t, uint8_t)':

C:\Users\My\Documents\Arduino\libraries\ESPAsyncUDP\src\AsyncUDP.cpp:254:57: error: 'udp_set_multicast_netif_addr' was not declared in this scope

     udp_set_multicast_netif_addr(_pcb, multicast_if_addr);

                                                         ^

C:\Users\My\Documents\Arduino\libraries\ESPAsyncUDP\src\AsyncUDP.cpp:258:36: error: 'udp_set_multicast_ttl' was not declared in this scope

     udp_set_multicast_ttl(_pcb, ttl);

                                    ^

Mit der Version 2.4 klappt's hingegen wunderbar. Könnte man die Empfehlung bezüglich der zu verwendenden Version bitte entsprechend anpassen?

**Comment by wkraft-fablabka** [comment]
Hallo Thomas,

prima, dass Du Dich da auch ran machst!

Das Ganze verträgt auch neben der Doku noch ein paar "Schönheitsreparaturen".  Den Fehler, wie viele andere, hatte ich vor ein paar Wochen auch schon mal.  Im Zweifel half dann immer zur aktuellsten Arduino-IDE die GITHUB-Version der ESP-Umgebung zu installieren. Das hat etliche Fehler behoben.

Ich werde die Beschreibung auch dahingehend anpassen.

Lukas, Philip: Könnt Ihr Thomas auch in die Github-Fablab-Crew aufnehmen, dann kann er ggf. auch gleich Verbesserungen vornehmen!


Gruß

  Wolfgang

	

------
In Antwort auf die folgende Mail

**Comment by tbaetzler** [comment]
Hi Wolfgang,

Ich habe den Build auch mit der Version 2.4 von ESP8266 getestet; der
hat auf Anhieb und ohne Mucken funktioniert.

Des weiteren ist mir unklar, ob ich in der IDE irgendwo angeben kann,
daß er das Library-Verzeichnis in meinem Projektverzeichnis zusätzlich
benutzen soll - ich habe mir so beholfen, daß ich die Bibliotheken in's
Library-Verzeichnis des Arduino-Ordners verschoben habe. Dorthin habe
ich auch die anderen Bibliotheken per git geclont.

Können bzw. dürfen bzw. wollen wir die als "git submodule" in das
Projekt integrieren?

Bis ich soweit bin, daß ich irgendwo etwas reparieren kann, dauert evtl.
noch ein bisschen.

Könnte passieren, daß ich Dir in den nächsten Tagen mal auflauere. Ich
habe da ein paar Fragen zum Thema SPI und ESP8266... ;-)

Ciao,
Thomas


Am 31.01.2018 um 08:21 schrieb wkraft-fablabka:
