### ISSUE TITLE
Missing dependencies in libraries/

### ISSUE THREAD

**Issue by koppa** [fablab-ka/PHABLABS-POV#2]
I just tried to compile the application and the following dependencies are missing

        libraries/ESPAsyncTCP/
        libraries/ESPAsyncUDP/
        libraries/Time/
        libraries/Timezone/

The timezone library from <https://github.com/JChristensen/Timezone> triggers  this warning. Is it still working correctly?

```WARNING: library Timezone claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (esp8266) architecture(s).```

**Comment by wkraft-fablabka** [comment]
The libraries are listen in the README.md

I receive  the same warning from Timezone, but only on two from four machines, where i compiled the sketch.
